"""add cooking_device to user and recipe

Revision ID: 1ac61d3d2e72
Revises: a8bf1936e54e
Create Date: 2026-04-01 12:00:24.333612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac61d3d2e72'
down_revision = 'a8bf1936e54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooking_device', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooking_device', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cooking_device')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('cooking_device')

    # ### end Alembic commands ###
