"""add gender to user

Revision ID: 616216fa096e
Revises: 22c399fc6dfc
Create Date: 2026-03-03 16:20:47.556280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616216fa096e'
down_revision = '22c399fc6dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
