"""add_new_dietary_filter_columns

Revision ID: a8bf1936e54e
Revises: 1578c60b2368
Create Date: 2026-03-27 13:58:56.523368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bf1936e54e'
down_revision = '1578c60b2368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_gluten_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_dairy_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_nut_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_egg_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_low_sugar', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_high_protein', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_mediterranean', sa.Boolean(), nullable=True))

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_gluten_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_dairy_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_nut_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_egg_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_low_sugar', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_high_protein', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_mediterranean', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('is_mediterranean')
        batch_op.drop_column('is_high_protein')
        batch_op.drop_column('is_low_sugar')
        batch_op.drop_column('is_egg_free')
        batch_op.drop_column('is_nut_free')
        batch_op.drop_column('is_dairy_free')
        batch_op.drop_column('is_gluten_free')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('is_mediterranean')
        batch_op.drop_column('is_high_protein')
        batch_op.drop_column('is_low_sugar')
        batch_op.drop_column('is_egg_free')
        batch_op.drop_column('is_nut_free')
        batch_op.drop_column('is_dairy_free')
        batch_op.drop_column('is_gluten_free')

    # ### end Alembic commands ###
