"""feedback per recipe

Revision ID: ce1ce3650ec2
Revises: af0ac92371b5
Create Date: 2026-03-05 15:10:40.863469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1ce3650ec2'
down_revision = 'af0ac92371b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('feedback_concern_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'])
        batch_op.drop_column('concern_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concern_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('feedback_concern_id_fkey'), 'health_concern', ['concern_id'], ['id'])
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
